import { Fragrance } from "./types";

/**
 * Sample catalog. In production this table is populated by a nightly sync job
 * from a fragrance data API (Fragella / FragDB) — see Aura-Technical-Plan.md.
 * The shape below mirrors one row of that synced `fragrances` table.
 */
export const FRAGRANCES: Fragrance[] = [
  { id: 1, name: "Baccarat Rouge 540", brand: "MFK", family: "oriental", gender: "Unisex", season: "Fall", occasion: "Evening", rating: 4.6, isNew: false, popularity: 98, top: ["Saffron", "Jasmine"], heart: ["Amberwood", "Ambergris"], base: ["Fir resin", "Cedar"], retailer: "Sephora", buyUrl: "https://www.sephora.com/search?keyword=Baccarat%20Rouge%20540" },
  { id: 2, name: "Santal 33", brand: "Le Labo", family: "woody", gender: "Unisex", season: "All", occasion: "Daily", rating: 4.4, isNew: false, popularity: 95, top: ["Cardamom", "Violet"], heart: ["Iris", "Ambrox"], base: ["Sandalwood", "Cedar", "Leather"], retailer: "Le Labo", buyUrl: "https://www.lelabofragrances.com/santal-33.html" },
  { id: 3, name: "Black Opium", brand: "YSL", family: "gourmand", gender: "Women", season: "Winter", occasion: "Evening", rating: 4.3, isNew: false, popularity: 92, top: ["Pink pepper", "Orange blossom"], heart: ["Coffee", "Jasmine"], base: ["Vanilla", "Patchouli"], retailer: "Sephora", buyUrl: "https://www.sephora.com/search?keyword=Black%20Opium" },
  { id: 4, name: "Light Blue", brand: "Dolce & Gabbana", family: "citrus", gender: "Women", season: "Summer", occasion: "Daily", rating: 4.1, isNew: false, popularity: 88, top: ["Sicilian lemon", "Apple"], heart: ["Bamboo", "White rose"], base: ["Cedar", "Amber", "Musk"], retailer: "FragranceNet", buyUrl: "https://www.fragrancenet.com/search?q=light+blue" },
  { id: 5, name: "Bleu de Chanel", brand: "Chanel", family: "woody", gender: "Men", season: "All", occasion: "Office", rating: 4.5, isNew: false, popularity: 94, top: ["Grapefruit", "Lemon", "Mint"], heart: ["Ginger", "Jasmine"], base: ["Sandalwood", "Cedar", "Incense"], retailer: "Chanel", buyUrl: "https://www.chanel.com/us/fragrance/c/bleu-de-chanel/" },
  { id: 6, name: "Good Girl", brand: "Carolina Herrera", family: "oriental", gender: "Women", season: "Fall", occasion: "Evening", rating: 4.2, isNew: false, popularity: 85, top: ["Almond", "Coffee"], heart: ["Tuberose", "Jasmine"], base: ["Tonka bean", "Cacao"], retailer: "Sephora", buyUrl: "https://www.sephora.com/search?keyword=Good%20Girl" },
  { id: 7, name: "Aventus", brand: "Creed", family: "fresh", gender: "Men", season: "Spring", occasion: "Office", rating: 4.6, isNew: false, popularity: 91, top: ["Pineapple", "Bergamot", "Blackcurrant"], heart: ["Birch", "Patchouli"], base: ["Musk", "Oakmoss", "Vanilla"], retailer: "Creed", buyUrl: "https://www.creedboutique.com/products/aventus" },
  { id: 8, name: "Libre", brand: "YSL", family: "floral", gender: "Women", season: "Spring", occasion: "Daily", rating: 4.2, isNew: false, popularity: 83, top: ["Lavender", "Mandarin"], heart: ["Orange blossom", "Jasmine"], base: ["Vanilla", "Musk", "Cedar"], retailer: "Sephora", buyUrl: "https://www.sephora.com/search?keyword=Libre" },
  { id: 9, name: "Cloud", brand: "Ariana Grande", family: "gourmand", gender: "Women", season: "All", occasion: "Daily", rating: 4.0, isNew: false, popularity: 80, top: ["Lavender", "Pear", "Bergamot"], heart: ["Whipped cream", "Praline"], base: ["Musk", "Woods"], retailer: "Ulta", buyUrl: "https://www.ulta.com/shop/fragrance?q=cloud" },
  { id: 10, name: "Oud Wood", brand: "Tom Ford", family: "woody", gender: "Unisex", season: "Winter", occasion: "Evening", rating: 4.5, isNew: false, popularity: 87, top: ["Oud", "Rosewood", "Cardamom"], heart: ["Sandalwood", "Vetiver"], base: ["Tonka", "Amber", "Vanilla"], retailer: "Sephora", buyUrl: "https://www.sephora.com/search?keyword=Tom%20Ford%20Oud%20Wood" },
  { id: 11, name: "Solar Bloom", brand: "Maison Aura", family: "floral", gender: "Women", season: "Spring", occasion: "Daily", rating: 4.4, isNew: true, popularity: 60, top: ["Neroli", "Mandarin"], heart: ["Peony", "Magnolia"], base: ["White musk", "Blonde wood"], retailer: "Sephora", buyUrl: "https://www.sephora.com/" },
  { id: 12, name: "Velvet Ember", brand: "Atelier Noir", family: "oriental", gender: "Unisex", season: "Winter", occasion: "Evening", rating: 4.5, isNew: true, popularity: 58, top: ["Saffron", "Plum"], heart: ["Rose", "Incense"], base: ["Amber", "Oud", "Vanilla"], retailer: "Nordstrom", buyUrl: "https://www.nordstrom.com/sr?keyword=fragrance" },
  { id: 13, name: "Citrine", brand: "Lumen", family: "citrus", gender: "Unisex", season: "Summer", occasion: "Daily", rating: 4.2, isNew: true, popularity: 55, top: ["Yuzu", "Grapefruit", "Verbena"], heart: ["Neroli", "Green tea"], base: ["White amber", "Musk"], retailer: "Ulta", buyUrl: "https://www.ulta.com/shop/fragrance" },
  { id: 14, name: "Cashmere Glow", brand: "Maison Aura", family: "gourmand", gender: "Women", season: "Fall", occasion: "Evening", rating: 4.3, isNew: true, popularity: 57, top: ["Pear", "Pink pepper"], heart: ["Orris", "Salted caramel"], base: ["Tonka", "Sandalwood", "Vanilla"], retailer: "Sephora", buyUrl: "https://www.sephora.com/" },
  { id: 15, name: "Coastal Linen", brand: "Lumen", family: "fresh", gender: "Unisex", season: "Summer", occasion: "Daily", rating: 4.1, isNew: true, popularity: 52, top: ["Sea salt", "Bergamot"], heart: ["Sage", "Lavender"], base: ["Driftwood", "Ambrette"], retailer: "Nordstrom", buyUrl: "https://www.nordstrom.com/sr?keyword=fragrance" },
  { id: 16, name: "Noir Santal", brand: "Atelier Noir", family: "woody", gender: "Men", season: "Fall", occasion: "Office", rating: 4.4, isNew: true, popularity: 54, top: ["Black pepper", "Bergamot"], heart: ["Cypress", "Geranium"], base: ["Sandalwood", "Vetiver", "Leather"], retailer: "Nordstrom", buyUrl: "https://www.nordstrom.com/sr?keyword=fragrance" },
];

export const getFragrance = (id: number) =>
  FRAGRANCES.find((f) => f.id === id);
